import Database from "better-sqlite3";
import {afterEach,expect,it} from "vitest";
import {SessionRepository} from "@/lib/server/persistence/session-repository";
import {EmailOutboxRepository} from "@/lib/server/email/email-outbox-repository";
const stores:SessionRepository[]=[];afterEach(()=>stores.splice(0).forEach(store=>store.close()));
function setup(){const sessions=new SessionRepository(":memory:");stores.push(sessions);const db=sessions.getDatabase();const now=new Date().toISOString();db.prepare("INSERT INTO schedules (id,name,start_date,local_time,timezone,repeat_days,prompt,device_serial,log_directory,status,next_run_at,completed_occurrences,created_at,updated_at) VALUES ('s','job','2026-01-01','08:00','UTC',1,'goal','dev','C:/tmp','active',NULL,0,?,?)").run(now,now);db.prepare("INSERT INTO schedule_occurrences (id,schedule_id,scheduled_for,status,created_at,updated_at) VALUES ('o','s',?,'completed',?,?)").run(now,now,now);return{db,outbox:new EmailOutboxRepository(db)}}
const input={occurrenceId:"o",configSnapshot:{enabled:true,to:"owner@example.test",subject:"Result",accountIdentity:"a".repeat(64)},resultSnapshot:{status:"completed"},attachmentContent:Buffer.from("report"),attachmentName:"job.txt",attachmentSha256:"b".repeat(64),messageId:"<o@android-agent.local>"};
it("deduplicates one notification per occurrence and claims atomically",()=>{const {outbox}=setup();const first=outbox.enqueue(input),second=outbox.enqueue(input);expect(second?.id).toBe(first?.id);const claimed=outbox.claim("worker",new Date("2099-01-01T00:00:00Z"));expect(claimed?.attempts).toBe(1);expect(outbox.claim("other",new Date("2099-01-01T00:00:01Z"))).toBeNull();expect(outbox.markSent(claimed!.id,"other",new Date().toISOString())).toBeNull();expect(outbox.markSent(claimed!.id,"worker",new Date().toISOString())?.status).toBe("sent")});
it("reclaims expired lease and supports explicit retry",()=>{const {outbox}=setup();const item=outbox.enqueue(input)!;const claimed=outbox.claim("first",new Date("2099-01-01T00:00:00Z"),1000)!;expect(outbox.claim("second",new Date("2099-01-01T00:00:02Z"))?.attempts).toBe(2);outbox.markFinal(item.id,"second","delivery_unknown","SMTP_UNKNOWN","unknown");expect(outbox.retry(item.id)).toBe(true);expect(outbox.get(item.id)?.status).toBe("pending")});
it("marks an expired sending lease unknown instead of blindly resending",()=>{const {outbox}=setup(),item=outbox.enqueue(input)!,claimed=outbox.claim("first",new Date("2099-01-01T00:00:00Z"),1000)!;outbox.markSending(claimed.id,"first");expect(outbox.claim("second",new Date("2099-01-01T00:00:02Z"))).toBeNull();expect(outbox.get(item.id)).toMatchObject({status:"delivery_unknown",errorCode:"SMTP_PROCESS_INTERRUPTED"})});
it("cancels unsent notifications before deleting a schedule",()=>{const {outbox}=setup();const item=outbox.enqueue(input)!;expect(outbox.cancelForSchedule("s")).toBe(1);expect(outbox.get(item.id)?.status).toBe("cancelled")});
