import {expect,it,vi} from "vitest";
import {EmailWorker} from "@/lib/server/email/email-worker";
const settings={host:"smtp.example.test",port:587,security:"starttls" as const,username:"agent@example.test",defaultRecipient:"owner@example.test",passwordConfigured:true,accountIdentity:"a".repeat(64),verifiedAt:null};
function item(attempts=1){return{id:"out",occurrenceId:"occ",notificationType:"job-result" as const,configSnapshot:{to:"owner@example.test",subject:"Result",accountIdentity:settings.accountIdentity},resultSnapshot:{body:"result",scheduleId:"schedule"},attachmentContent:Buffer.from("report"),attachmentName:"job.txt",attachmentEncoding:"utf8",attachmentSha256:"b".repeat(64),status:"preparing" as const,attempts,nextAttemptAt:null,leaseOwner:"worker",leaseExpiresAt:null,messageId:"<out@local>",sentAt:null,errorCode:null,redactedErrorMessage:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
it("marks SMTP accepted using a fake sender and never calls network transport",async()=>{const record=item(),repository={sentSince:vi.fn(()=>0),claim:vi.fn(()=>record),markSending:vi.fn(()=>record),markSent:vi.fn(),markRetry:vi.fn(),markFinal:vi.fn(),get:vi.fn(()=>record)} as any,sender=vi.fn(async()=>({messageId:record.messageId!}));await new EmailWorker(repository,sender,()=>new Date("2026-01-01T00:00:00Z"),async()=>settings).processOne();expect(sender).toHaveBeenCalledOnce();expect(repository.markSent).toHaveBeenCalledWith(record.id,expect.any(String),"2026-01-01T00:00:00.000Z")});
it("does not send when a claimed email was cancelled before SMTP sending",async()=>{const record=item(),repository={sentSince:vi.fn(()=>0),claim:vi.fn(()=>record),markFinal:vi.fn(),markSending:vi.fn(()=>null)} as any,sender=vi.fn();await new EmailWorker(repository,sender,()=>new Date(),async()=>settings).processOne();expect(sender).not.toHaveBeenCalled()});
it("halts claims after thirty SMTP accepts within the last hour",async()=>{const repository={sentSince:vi.fn(()=>30),claim:vi.fn()} as any,sender=vi.fn();expect(await new EmailWorker(repository,sender,()=>new Date("2026-01-01T01:00:00Z"),async()=>settings).processOne()).toBeNull();expect(repository.sentSince).toHaveBeenCalledWith("2026-01-01T00:00:00.000Z");expect(repository.claim).not.toHaveBeenCalled();expect(sender).not.toHaveBeenCalled()});
it("blocks when sender account identity changed without invoking SMTP",async()=>{const record=item(),repository={sentSince:vi.fn(()=>0),claim:vi.fn(()=>record),markFinal:vi.fn()} as any,sender=vi.fn();await new EmailWorker(repository,sender,()=>new Date(),async()=>({...settings,accountIdentity:"c".repeat(64)})).processOne();expect(sender).not.toHaveBeenCalled();expect(repository.markFinal).toHaveBeenCalledWith(record.id,expect.any(String),"blocked_config","EMAIL_CONFIG_CHANGED",expect.any(String))});
it("retries temporary pre-accept failures and marks post-DATA ambiguity unknown",async()=>{for(const [error,method] of [[Object.assign(new Error("offline"),{code:"ECONNREFUSED"}),"markRetry"],[Object.assign(new Error("socket closed after DATA"),{code:"ECONNRESET"}),"markFinal"]] as const){const record=item(),repository={sentSince:vi.fn(()=>0),claim:vi.fn(()=>record),markSending:vi.fn(()=>record),get:vi.fn(()=>record),markRetry:vi.fn(),markFinal:vi.fn()} as any;await new EmailWorker(repository,async()=>{throw error},()=>new Date("2026-01-01T00:00:00Z"),async()=>settings).processOne();expect(repository[method]).toHaveBeenCalled()}});
