import {afterEach,describe,expect,it,vi} from "vitest";import fs from "node:fs";import os from "node:os";import path from "node:path";import {SessionRepository} from "@/lib/server/persistence/session-repository";import {ScheduleRepository} from "@/lib/server/schedule/schedule-repository";import {ScheduleService} from "@/lib/server/schedule/schedule-service";
const dirs:string[]=[];afterEach(()=>dirs.splice(0).forEach(d=>fs.rmSync(d,{recursive:true,force:true})));const setup=()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),dir=fs.mkdtempSync(path.join(os.tmpdir(),"scheduler-int-"));dirs.push(dir);return{sessions,repo,item:repo.create({name:"Due",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Do it",deviceSerial:"SERIAL",logDirectory:dir,nextRunAt:"2026-09-08T01:00:00.000Z"})}};
import {eventBus} from "@/lib/server/event-bus";
describe("ScheduleService",()=>{
 it.each(["scheduled","run-now"] as const)("includes chat navigation data when %s starts",async(mode)=>{
  const {sessions,repo,item}=setup();
  const events:unknown[]=[];
  const unsubscribe=eventBus.subscribe(event=>{if(event.type==="schedule.updated")events.push(event.data)});
  try{
   const runs={createAndStart:vi.fn(async({conversationId,deviceSerial,goal,maxSteps})=>sessions.createRun(conversationId,deviceSerial,goal,maxSteps))};
   const service=new ScheduleService(repo,{write:vi.fn()} as never,()=>new Date("2026-09-08T01:01:00Z"),runs as never,sessions);
   if(mode==="scheduled"){await service.tick();await service.tick()}else await service.runNow(item);
   const occurrence=repo.get(item.id)!.occurrences[0];
   expect(events).toEqual([{scheduleId:item.id,occurrenceId:occurrence.id,status:"running",conversationId:occurrence.conversationId,runId:occurrence.runId,deviceSerial:"SERIAL"}]);
  }finally{unsubscribe();sessions.close()}
 });
 it("is idempotent across ticks",async()=>{const now=new Date("2026-09-08T01:01:00Z"),{sessions,repo,item}=setup(),runs={createAndStart:vi.fn(async({conversationId,deviceSerial,goal,maxSteps})=>sessions.createRun(conversationId,deviceSerial,goal,maxSteps))},service=new ScheduleService(repo,{write:vi.fn(async()=>"log") } as never,()=>now,runs as never,sessions);await service.tick();await service.tick();expect(runs.createAndStart).toHaveBeenCalledOnce();expect(repo.get(item.id)?.completedOccurrences).toBe(1);sessions.close()});
 it("stop waits for the active tick to drain",async()=>{const now=new Date("2026-09-08T01:01:00Z"),{sessions,repo}=setup();let release!:()=>void;const runs={createAndStart:vi.fn(()=>new Promise(resolve=>{release=()=>resolve(sessions.createRun(sessions.create("drain").id,"SERIAL","Do",1))}))},service=new ScheduleService(repo,{write:vi.fn()} as never,()=>now,runs as never,sessions);const tick=service.tick();await vi.waitFor(()=>expect(runs.createAndStart).toHaveBeenCalledOnce());let stopped=false;const stopping=service.stop().then(()=>{stopped=true});await Promise.resolve();expect(stopped).toBe(false);release();await tick;await stopping;expect(stopped).toBe(true);sessions.close()});
 it("stop drains an in-flight terminal event log write",async()=>{const now=new Date("2026-09-08T01:05:00Z"),{sessions,repo,item}=setup(),conversation=sessions.create("scheduled"),run=sessions.createRun(conversation.id,"SERIAL","Do",1),occ=repo.createOccurrence(item.id,item.nextRunAt!,"running");repo.updateOccurrence(occ.id,{runId:run.id,conversationId:conversation.id});sessions.updateRun(run.id,{status:"completed",result:"done",endedAt:now.toISOString()});let release!:()=>void;const writer={write:vi.fn(()=>new Promise<string>(resolve=>{release=()=>resolve("terminal.log")}))},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);service.start(60_000);eventBus.emit("run.completed",{runId:run.id});await vi.waitFor(()=>expect(writer.write).toHaveBeenCalled());let stopped=false;const stopping=service.stop().then(()=>{stopped=true});await Promise.resolve();expect(stopped).toBe(false);release();await stopping;expect(stopped).toBe(true);expect(repo.findOccurrence(occ.id)?.logFile).toBe("terminal.log");sessions.close()});
 it("marks late schedule missed",async()=>{const now=new Date("2026-09-08T02:00:00Z"),{sessions,repo,item}=setup(),writer={write:vi.fn(async()=>"missed")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);await service.tick();expect(repo.get(item.id)?.occurrences[0].status).toBe("missed");sessions.close()});
 it("waits when device busy",async()=>{const now=new Date("2026-09-08T01:01:00Z"),{sessions,repo,item}=setup(),service=new ScheduleService(repo,{write:vi.fn()} as never,()=>now,{createAndStart:vi.fn(async()=>{throw new Error("agent already active")})} as never,sessions);await service.tick();expect(repo.get(item.id)?.occurrences[0].status).toBe("waiting_device");sessions.close()});
 it("times out busy occurrence",async()=>{const now=new Date("2026-09-08T01:20:00Z"),{sessions,repo,item}=setup(),occ=repo.createOccurrence(item.id,item.nextRunAt!,"waiting_device"),writer={write:vi.fn(async()=>"busy")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);sessions.getDatabase().prepare("UPDATE schedule_occurrences SET created_at=? WHERE id=?").run("2026-09-08T01:00:00Z",occ.id);await service.tick();expect(repo.findOccurrence(occ.id)?.errorCode).toBe("DEVICE_BUSY_TIMEOUT");sessions.close()});
 it("reconciles terminal run",async()=>{const now=new Date("2026-09-08T01:05:00Z"),{sessions,repo,item}=setup(),conversation=sessions.create("scheduled"),run=sessions.createRun(conversation.id,"SERIAL","Do",1),occ=repo.createOccurrence(item.id,item.nextRunAt!,"running"),writer={write:vi.fn(async()=>"terminal")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);repo.updateOccurrence(occ.id,{runId:run.id,conversationId:conversation.id});sessions.updateRun(run.id,{status:"completed",result:"done",endedAt:now.toISOString()});await service.reconcile();expect(repo.findOccurrence(occ.id)?.result).toBe("done");expect(writer.write).toHaveBeenCalledOnce();sessions.close()});
 it("records offline device failure and advances",async()=>{const now=new Date("2026-09-08T01:01:00Z"),{sessions,repo,item}=setup(),writer={write:vi.fn(async()=>"offline")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn(async()=>{throw new Error("Device is offline")})} as never,sessions);await service.tick();expect(repo.get(item.id)?.occurrences[0].errorCode).toBe("DEVICE_UNAVAILABLE");expect(repo.get(item.id)?.completedOccurrences).toBe(1);sessions.close()});
 it("does not launch two schedules concurrently on the same busy device",async()=>{const now=new Date("2026-09-08T01:01:00Z"),first=setup(),second=first.repo.create({name:"Second",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Other",deviceSerial:"SERIAL",logDirectory:first.item.logDirectory,nextRunAt:first.item.nextRunAt}),runs={createAndStart:vi.fn().mockResolvedValueOnce(first.sessions.createRun(first.sessions.create("first").id,"SERIAL","Do",1)).mockRejectedValueOnce(new Error("agent already active"))},service=new ScheduleService(first.repo,{write:vi.fn()} as never,()=>now,runs as never,first.sessions);await service.tick();expect(runs.createAndStart).toHaveBeenCalledTimes(2);expect(first.repo.get(second.id)?.occurrences[0].status).toBe("waiting_device");first.sessions.close()});
 it("disables schedule after three consecutive log failures",async()=>{const now=new Date("2026-09-08T02:00:00Z"),{sessions,repo,item}=setup(),writer={write:vi.fn(async()=>{throw new Error("disk denied")})},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);for(let i=0;i<3;i++){const occ=repo.createOccurrence(item.id,new Date(Date.parse(item.nextRunAt!)+i).toISOString(),"failed");await (service as unknown as {write:(schedule:typeof item,occurrence:typeof occ)=>Promise<void>}).write(item,occ)}expect(repo.get(item.id)?.status).toBe("disabled");sessions.close()});
 it("run-now does not increase scheduled progress",async()=>{const now=new Date("2026-09-08T00:00:00Z"),{sessions,repo,item}=setup(),runs={createAndStart:vi.fn(async({conversationId,deviceSerial,goal,maxSteps})=>sessions.createRun(conversationId,deviceSerial,goal,maxSteps))},service=new ScheduleService(repo,{write:vi.fn()} as never,()=>now,runs as never,sessions);await service.runNow(item);expect(repo.get(item.id)?.completedOccurrences).toBe(0);expect(repo.get(item.id)?.nextRunAt).toBe(item.nextRunAt);sessions.close()});
 it("interval downtime creates one missed occurrence and jumps future",async()=>{const now=new Date("2026-09-08T03:01:00Z"),{sessions,repo,item}=setup();repo.update(item.id,{rule:{type:"interval",every:5,unit:"minutes"},occurrenceLimit:10,nextRunAt:"2026-09-08T01:00:00.000Z"});const writer={write:vi.fn(async()=>"missed")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);await service.tick();const updated=repo.get(item.id)!;expect(updated.occurrences).toHaveLength(1);expect(updated.completedOccurrences).toBe(1);expect(Date.parse(updated.nextRunAt!)).toBeGreaterThan(now.getTime());sessions.close()});
});
