import {describe,expect,it} from "vitest";
import Database from "better-sqlite3";
import fs from "node:fs";import os from "node:os";import path from "node:path";
import {firstOccurrence,nextFutureOccurrence,nextOccurrence,previewOccurrences} from "@/lib/server/schedule/schedule-calculator";
import {SessionRepository} from "@/lib/server/persistence/session-repository";import {ScheduleRepository} from "@/lib/server/schedule/schedule-repository";import {scheduleInputSchema} from "@/lib/contracts/schemas";
const base={startDate:"2026-09-04",localTime:"08:00",timezone:"Asia/Bangkok",occurrenceLimit:5};
describe("schedule rules",()=>{
 it("calculates fixed duration intervals",()=>{expect(nextOccurrence({...base,rule:{type:"interval",every:30,unit:"minutes"},completedOccurrences:1},"2026-09-04T01:45:00.000Z")).toBe("2026-09-04T02:15:00.000Z");expect(nextOccurrence({...base,rule:{type:"interval",every:3,unit:"hours"},completedOccurrences:1},"2026-09-04T23:00:00.000Z")).toBe("2026-09-05T02:00:00.000Z")});
 it("handles calendar intervals and leap days",()=>{const seconds={...base,rule:{type:"interval",every:30,unit:"seconds"} as const,completedOccurrences:1};expect(nextOccurrence(seconds,firstOccurrence(seconds))).toBe("2026-09-04T01:00:30.000Z");const leap={...base,startDate:"2028-02-28",rule:{type:"daily"} as const,completedOccurrences:1};expect(nextOccurrence(leap,firstOccurrence(leap))).toBe("2028-02-29T01:00:00.000Z")});
 it("finds and advances weekly day",()=>{const rule={...base,rule:{type:"weekly" as const,weekdays:[3] as (1|2|3|4|5|6|7)[]},completedOccurrences:0},first=firstOccurrence(rule);expect(first).toBe("2026-09-09T01:00:00.000Z");expect(nextOccurrence({...rule,completedOccurrences:1},first)).toBe("2026-09-16T01:00:00.000Z")});
 it("stops and previews consistently",()=>{expect(nextOccurrence({...base,rule:{type:"weekly",weekdays:[1]},occurrenceLimit:5,completedOccurrences:5})).toBeNull();expect(previewOccurrences({...base,rule:{type:"daily"},completedOccurrences:0},3)).toEqual(["2026-09-04T01:00:00.000Z","2026-09-05T01:00:00.000Z","2026-09-06T01:00:00.000Z"])});
 it("validates variants strictly",()=>{const common={name:"Test",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",occurrenceLimit:3,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs"};expect(scheduleInputSchema.safeParse({...common,occurrenceLimit:null,rule:{type:"daily"}}).success).toBe(true);expect(scheduleInputSchema.safeParse({...common,occurrenceLimit:null,rule:{type:"weekly",weekdays:[2,5]}}).success).toBe(true);expect(scheduleInputSchema.safeParse({...common,occurrenceLimit:null,rule:{type:"interval",every:5,unit:"minutes"}}).success).toBe(true);expect(scheduleInputSchema.safeParse({...common,rule:{type:"interval",every:0,unit:"minutes"}}).success).toBe(false);expect(scheduleInputSchema.safeParse({...common,rule:{type:"daily",weekdays:[1]}}).success).toBe(false);expect(scheduleInputSchema.safeParse({...common,rule:{type:"weekly",weekdays:[8]}}).success).toBe(false)});
 it("skips interval backlog",()=>{const rule={...base,rule:{type:"interval",every:5,unit:"minutes"} as const,completedOccurrences:1};expect(nextFutureOccurrence(rule,"2026-09-04T01:00:00.000Z","2026-09-04T02:01:00.000Z")).toBe("2026-09-04T02:05:00.000Z")});
 it("clears obsolete rule columns",()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),item=repo.create({name:"Rule",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"interval",every:30,unit:"minutes"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs",nextRunAt:"2026-09-08T01:00:00.000Z"});repo.update(item.id,{rule:{type:"weekly",weekdays:[5]}});expect(sessions.getDatabase().prepare("SELECT interval_value,interval_unit,weekly_day,weekly_days FROM schedules WHERE id=?").get(item.id)).toEqual({interval_value:null,interval_unit:null,weekly_day:5,weekly_days:"[5]"});sessions.close()});
 it("keeps interval active without an occurrence limit",()=>{const schedule={...base,rule:{type:"interval",every:1,unit:"seconds"} as const,occurrenceLimit:null,completedOccurrences:100000};expect(nextOccurrence(schedule,"2026-09-04T01:00:00.000Z")).toBe("2026-09-04T01:00:01.000Z");const common={name:"Infinite",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\\logs"};expect(scheduleInputSchema.safeParse({...common,rule:{type:"interval",every:1,unit:"seconds"},occurrenceLimit:null}).success).toBe(true);expect(scheduleInputSchema.safeParse({...common,rule:{type:"weekly",weekdays:[1]},occurrenceLimit:5}).success).toBe(false)});
 it("keeps daily active without occurrence limit",()=>{const schedule={...base,rule:{type:"daily"} as const,occurrenceLimit:null,completedOccurrences:999};expect(nextOccurrence(schedule,"2026-09-04T01:00:00.000Z")).toBe("2026-09-05T01:00:00.000Z");const common={name:"Daily",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\\logs"};expect(scheduleInputSchema.safeParse({...common,rule:{type:"daily"},occurrenceLimit:null}).success).toBe(true);expect(scheduleInputSchema.safeParse({...common,rule:{type:"daily"},occurrenceLimit:5}).success).toBe(false)});
});
