import {afterEach,describe,expect,it,vi} from "vitest";import fs from "node:fs";import os from "node:os";import path from "node:path";import {SessionRepository} from "@/lib/server/persistence/session-repository";import {ScheduleRepository} from "@/lib/server/schedule/schedule-repository";import {ScheduleService} from "@/lib/server/schedule/schedule-service";
const dirs:string[]=[];afterEach(()=>dirs.splice(0).forEach(d=>fs.rmSync(d,{recursive:true,force:true})));const setup=()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),dir=fs.mkdtempSync(path.join(os.tmpdir(),"scheduler-int-"));dirs.push(dir);return{sessions,repo,item:repo.create({name:"Due",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",repeatDays:2,prompt:"Do it",deviceSerial:"SERIAL",logDirectory:dir,nextRunAt:"2026-09-08T01:00:00.000Z"})}};
describe("ScheduleService",()=>{
 it("is idempotent across ticks",async()=>{const now=new Date("2026-09-08T01:01:00Z"),{sessions,repo,item}=setup(),runs={createAndStart:vi.fn(async({conversationId,deviceSerial,goal,maxSteps})=>sessions.createRun(conversationId,deviceSerial,goal,maxSteps))},service=new ScheduleService(repo,{write:vi.fn(async()=>"log") } as never,()=>now,runs as never,sessions);await service.tick();await service.tick();expect(runs.createAndStart).toHaveBeenCalledOnce();expect(repo.get(item.id)?.completedOccurrences).toBe(1);sessions.close()});
 it("marks late schedule missed",async()=>{const now=new Date("2026-09-08T02:00:00Z"),{sessions,repo,item}=setup(),writer={write:vi.fn(async()=>"missed")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);await service.tick();expect(repo.get(item.id)?.occurrences[0].status).toBe("missed");sessions.close()});
 it("waits when device busy",async()=>{const now=new Date("2026-09-08T01:01:00Z"),{sessions,repo,item}=setup(),service=new ScheduleService(repo,{write:vi.fn()} as never,()=>now,{createAndStart:vi.fn(async()=>{throw new Error("agent already active")})} as never,sessions);await service.tick();expect(repo.get(item.id)?.occurrences[0].status).toBe("waiting_device");sessions.close()});
 it("times out busy occurrence",async()=>{const now=new Date("2026-09-08T01:20:00Z"),{sessions,repo,item}=setup(),occ=repo.createOccurrence(item.id,item.nextRunAt!,"waiting_device"),writer={write:vi.fn(async()=>"busy")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);sessions.getDatabase().prepare("UPDATE schedule_occurrences SET created_at=? WHERE id=?").run("2026-09-08T01:00:00Z",occ.id);await service.tick();expect(repo.findOccurrence(occ.id)?.errorCode).toBe("DEVICE_BUSY_TIMEOUT");sessions.close()});
 it("reconciles terminal run",async()=>{const now=new Date("2026-09-08T01:05:00Z"),{sessions,repo,item}=setup(),conversation=sessions.create("scheduled"),run=sessions.createRun(conversation.id,"SERIAL","Do",1),occ=repo.createOccurrence(item.id,item.nextRunAt!,"running"),writer={write:vi.fn(async()=>"terminal")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);repo.updateOccurrence(occ.id,{runId:run.id,conversationId:conversation.id});sessions.updateRun(run.id,{status:"completed",result:"done",endedAt:now.toISOString()});await service.reconcile();expect(repo.findOccurrence(occ.id)?.result).toBe("done");expect(writer.write).toHaveBeenCalledOnce();sessions.close()});
 it("records offline device failure and advances",async()=>{const now=new Date("2026-09-08T01:01:00Z"),{sessions,repo,item}=setup(),writer={write:vi.fn(async()=>"offline")},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn(async()=>{throw new Error("Device is offline")})} as never,sessions);await service.tick();expect(repo.get(item.id)?.occurrences[0].errorCode).toBe("DEVICE_UNAVAILABLE");expect(repo.get(item.id)?.completedOccurrences).toBe(1);sessions.close()});
 it("does not launch two schedules concurrently on the same busy device",async()=>{const now=new Date("2026-09-08T01:01:00Z"),first=setup(),second=first.repo.create({name:"Second",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",repeatDays:1,prompt:"Other",deviceSerial:"SERIAL",logDirectory:first.item.logDirectory,nextRunAt:first.item.nextRunAt}),runs={createAndStart:vi.fn().mockResolvedValueOnce(first.sessions.createRun(first.sessions.create("first").id,"SERIAL","Do",1)).mockRejectedValueOnce(new Error("agent already active"))},service=new ScheduleService(first.repo,{write:vi.fn()} as never,()=>now,runs as never,first.sessions);await service.tick();expect(runs.createAndStart).toHaveBeenCalledTimes(2);expect(first.repo.get(second.id)?.occurrences[0].status).toBe("waiting_device");first.sessions.close()});
 it("disables schedule after three consecutive log failures",async()=>{const now=new Date("2026-09-08T02:00:00Z"),{sessions,repo,item}=setup(),writer={write:vi.fn(async()=>{throw new Error("disk denied")})},service=new ScheduleService(repo,writer as never,()=>now,{createAndStart:vi.fn()} as never,sessions);for(let i=0;i<3;i++){const occ=repo.createOccurrence(item.id,new Date(Date.parse(item.nextRunAt!)+i).toISOString(),"failed");await (service as unknown as {write:(schedule:typeof item,occurrence:typeof occ)=>Promise<void>}).write(item,occ)}expect(repo.get(item.id)?.status).toBe("disabled");sessions.close()});
});
