import {afterEach,describe,expect,it} from "vitest";
import fs from "node:fs";import os from "node:os";import path from "node:path";
import {SessionRepository} from "@/lib/server/persistence/session-repository";import {ScheduleRepository} from "@/lib/server/schedule/schedule-repository";import {localDateTimeToUtc,previewOccurrences,nextOccurrence} from "@/lib/server/schedule/schedule-calculator";import {validateLogDirectory} from "@/lib/server/schedule/schedule-validation";import {scheduleInputSchema} from "@/lib/contracts/schemas";import {ScheduleLogWriter} from "@/lib/server/schedule/schedule-log-writer";import type {Schedule,ScheduleOccurrence} from "@/lib/contracts/types";
const dirs:string[]=[];afterEach(()=>dirs.splice(0).forEach(dir=>fs.rmSync(dir,{recursive:true,force:true})));
describe("schedule feature",()=>{
 it("calculates inclusive days",()=>{expect(localDateTimeToUtc("2026-09-08","08:00","Asia/Bangkok")).toBe("2026-09-08T01:00:00.000Z");expect(previewOccurrences({startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null})).toHaveLength(3)});
 it("deduplicates occurrences",()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),item=repo.create({name:"Daily",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs",nextRunAt:"2026-09-08T01:00:00.000Z"});expect(repo.createOccurrence(item.id,item.nextRunAt!).id).toBe(repo.createOccurrence(item.id,item.nextRunAt!).id);expect(nextOccurrence({...item,rule:{type:"weekly",weekdays:[2]},occurrenceLimit:1,completedOccurrences:1})).toBeNull();sessions.close()});
 it("persists pause and resume",()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),item=repo.create({name:"Pause",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs",nextRunAt:"2026-09-08T01:00:00.000Z"});repo.update(item.id,{status:"paused"});expect(repo.get(item.id)?.nextRunAt).toBe(item.nextRunAt);repo.update(item.id,{status:"active"});expect(repo.get(item.id)?.completedOccurrences).toBe(0);sessions.close()});
 it("retains schedule links after conversation deletion",()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),item=repo.create({name:"History",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs",nextRunAt:"2026-09-08T01:00:00.000Z"}),conversation=sessions.create("scheduled"),run=sessions.createRun(conversation.id,"SERIAL","Test",1),occ=repo.createOccurrence(item.id,item.nextRunAt!);repo.updateOccurrence(occ.id,{status:"completed",conversationId:conversation.id,runId:run.id});sessions.updateRun(run.id,{status:"completed",endedAt:new Date().toISOString()});sessions.deleteConversation(conversation.id);expect(repo.get(item.id)?.occurrences[0].runId).toBe(run.id);sessions.close()});
 it("prunes only old terminal occurrences",()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),item=repo.create({name:"Retention",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs",nextRunAt:"2026-09-08T01:00:00.000Z"}),old=repo.createOccurrence(item.id,"2025-01-01T01:00:00.000Z","completed"),pending=repo.createOccurrence(item.id,item.nextRunAt!);sessions.getDatabase().prepare("UPDATE schedule_occurrences SET updated_at=? WHERE id=?").run("2025-01-01T00:00:00.000Z",old.id);expect(repo.pruneOccurrences(365)).toBe(1);expect(repo.findOccurrence(pending.id)?.status).toBe("pending");sessions.close()});
 it("validates path and redacts log secrets",async()=>{await expect(validateLogDirectory("relative/logs")).rejects.toThrow();const dir=fs.mkdtempSync(path.join(os.tmpdir(),"schedule-test-"));dirs.push(dir);const item={id:"12345678-abcd",name:"Log",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"sk-abcdefghijklmnopqrstuvwxyz",deviceSerial:"SERIAL",logDirectory:dir,status:"active",nextRunAt:null,completedOccurrences:0,createdAt:"",updatedAt:""} satisfies Schedule,occ={id:"occ",scheduleId:item.id,scheduledFor:"2026-09-08T01:00:00.000Z",status:"completed",conversationId:null,runId:null,startedAt:null,endedAt:null,result:"ok",errorCode:null,errorMessage:null,logFile:null,createdAt:"",updatedAt:""} satisfies ScheduleOccurrence;const file=await new ScheduleLogWriter().write(item,occ);expect(fs.readFileSync(file,"utf8")).toContain("[REDACTED]")});
 it("migrates legacy occurrence foreign keys without losing rows",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"schedule-db-"));dirs.push(dir);const dbPath=path.join(dir,"sessions.sqlite");const first=new SessionRepository(dbPath),repo=new ScheduleRepository(first.getDatabase()),item=repo.create({name:"Migration",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs",nextRunAt:"2026-09-08T01:00:00.000Z"}),conversation=first.create("scheduled"),run=first.createRun(conversation.id,"SERIAL","Test",1),occ=repo.createOccurrence(item.id,item.nextRunAt!);repo.updateOccurrence(occ.id,{conversationId:conversation.id,runId:run.id});first.close();const reopened=new SessionRepository(dbPath),repo2=new ScheduleRepository(reopened.getDatabase());expect(repo2.findOccurrence(occ.id)?.runId).toBe(run.id);reopened.close()});
 it("rejects invalid schedule fields",()=>{const valid={name:"Valid",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs"};expect(()=>scheduleInputSchema.parse({...valid,startDate:"bad"})).toThrow();expect(()=>scheduleInputSchema.parse({...valid,localTime:"25:70"})).toThrow();expect(()=>scheduleInputSchema.parse({...valid,rule:{type:"daily"},occurrenceLimit:0})).toThrow();expect(()=>scheduleInputSchema.parse({...valid,logDirectory:"C:\bad\u0000path"})).toThrow()});
 it("deleting schedule keeps generated conversation and run",()=>{const sessions=new SessionRepository(":memory:"),repo=new ScheduleRepository(sessions.getDatabase()),item=repo.create({name:"Delete",startDate:"2026-09-08",localTime:"08:00",timezone:"Asia/Bangkok",rule:{type:"daily"},occurrenceLimit:null,prompt:"Test",deviceSerial:"SERIAL",logDirectory:"C:\logs",nextRunAt:"2026-09-08T01:00:00.000Z"}),conversation=sessions.create("scheduled"),run=sessions.createRun(conversation.id,"SERIAL","Test",1),occ=repo.createOccurrence(item.id,item.nextRunAt!);repo.updateOccurrence(occ.id,{conversationId:conversation.id,runId:run.id});expect(repo.delete(item.id)).toBe(true);expect(sessions.get(conversation.id)?.runs[0].id).toBe(run.id);sessions.close()});
});
