import fs from "node:fs";
import path from "node:path";
import {describe,expect,it} from "vitest";

const root=process.cwd();
const read=(name:string)=>fs.readFileSync(path.join(root,name),"utf8");
describe("Windows background launcher security",()=>{
 it("keeps tray.ps1 UTF-8 BOM for Windows PowerShell 5",()=>{const bytes=fs.readFileSync(path.join(root,"scripts/windows/tray.ps1"));expect([...bytes.subarray(0,3)]).toEqual([0xef,0xbb,0xbf])});
 it("uses a C# stdin reader thread and releases the native HICON",()=>{const tray=read("scripts/windows/tray.ps1");expect(tray).toContain("public static Thread Start(TextReader input, ConcurrentQueue<string> queue)");expect(tray).toContain("[AndroidAgentTrayInput]::Start([Console]::In,$queue)");expect(tray).not.toMatch(/Task\]::Run|Task\.Run|\[Action\]\s*\{/);expect(tray).toContain("DestroyIcon($handle)");expect(tray.indexOf("Clone()")).toBeLessThan(tray.indexOf("DestroyIcon($handle)"))});
 it("never bypasses PowerShell execution policy",()=>{for(const file of ["lib/server/platform/windows/autostart.ts","lib/server/platform/windows/tray-controller.ts","scripts/start-background.ts","scripts/windows/autostart.ps1","scripts/windows/launch-background.ps1","scripts/windows/tray.ps1"])expect(read(file)).not.toMatch(/-ExecutionPolicy|Bypass|Unrestricted/i)});
 it("launches the production host directly without npm, cmd, or inherited stdio",()=>{const script=read("scripts/windows/launch-background.ps1");expect(script).toContain("UseShellExecute=$false");expect(script).toContain("CreateNoWindow=$true");expect(script).toContain("NODE_ENV']='production");expect(script).toContain("--host");expect(script).not.toMatch(/npm|cmd.exe|tsx watch/i)});
 it("uses an installation-owned current-user shortcut and verifies before deletion",()=>{const script=read("scripts/windows/autostart.ps1");expect(script).toContain("[Environment+SpecialFolder]::Startup");expect(script).toContain('Android Agent - $InstallationId.lnk');expect(script).toContain("if(-not (Valid $link))");expect(script).toContain("Refusing to remove an unverified shortcut");expect(script).not.toMatch(/ScheduledTask|CurrentVersion\Run|HKLM/i)});
 it("keeps service-opening imports behind the instance lock",()=>{const server=read("server.ts");expect(server.indexOf("acquireInstanceLock")).toBeLessThan(server.indexOf('import("./lib/server/application-lifecycle")'));expect(server).not.toMatch(/^import .*session-repository/m);const host=read("scripts/start-background.ts");expect(host.indexOf("acquireInstanceLock({appRoot")).toBeLessThan(host.indexOf('import("../lib/server/application-lifecycle")'))});
 it("injects signed real-peer context at the custom server boundary",()=>{const lifecycle=read("lib/server/application-lifecycle.ts");expect(lifecycle).toContain("createServer((request,response)=>{protectSystemApiPeerHeaders(request.headers,request.socket.remoteAddress)");expect(lifecycle.indexOf("protectSystemApiPeerHeaders(request.headers,request.socket.remoteAddress)")).toBeLessThan(lifecycle.indexOf("requestHandler(request,response)"))});
 it("closes admissions before scheduler and agent cleanup and guards launch entry points",()=>{const lifecycle=read("lib/server/application-lifecycle.ts"),runService=read("lib/server/agent/run-service.ts"),scheduler=read("lib/server/schedule/schedule-service.ts");expect(lifecycle.indexOf("stopApplicationAdmissions")).toBeLessThan(lifecycle.indexOf("scheduleService.stop()"));expect(runService).toContain("assertApplicationAcceptingWork()");expect(scheduler).toContain("assertApplicationAcceptingWork()");expect(scheduler).toContain("!isApplicationAcceptingWork()")});
});
