import "@/lib/server/server-guard";
import type Database from "better-sqlite3";
import {sessionRepository} from "@/lib/server/persistence/session-repository";
export type EmailOutboxStatus="pending"|"preparing"|"sending"|"retry_wait"|"sent"|"failed"|"blocked_config"|"attachment_failed"|"delivery_unknown"|"cancelled";
export type EmailOutboxRecord={id:string;occurrenceId:string;notificationType:"job-result";configSnapshot:Record<string,unknown>;resultSnapshot:Record<string,unknown>;attachmentContent:Buffer|null;attachmentName:string|null;attachmentEncoding:string;attachmentSha256:string|null;status:EmailOutboxStatus;attempts:number;nextAttemptAt:string|null;leaseOwner:string|null;leaseExpiresAt:string|null;messageId:string|null;sentAt:string|null;errorCode:string|null;redactedErrorMessage:string|null;createdAt:string;updatedAt:string};
type Row={id:string;occurrence_id:string;notification_type:"job-result";config_snapshot_json:string;result_snapshot_json:string;attachment_content:Buffer|null;attachment_name:string|null;attachment_encoding:string;attachment_sha256:string|null;status:EmailOutboxStatus;attempts:number;next_attempt_at:string|null;lease_owner:string|null;lease_expires_at:string|null;message_id:string|null;sent_at:string|null;error_code:string|null;redacted_error_message:string|null;created_at:string;updated_at:string};
const map=(row:Row):EmailOutboxRecord=>({id:row.id,occurrenceId:row.occurrence_id,notificationType:row.notification_type,configSnapshot:JSON.parse(row.config_snapshot_json),resultSnapshot:JSON.parse(row.result_snapshot_json),attachmentContent:row.attachment_content,attachmentName:row.attachment_name,attachmentEncoding:row.attachment_encoding,attachmentSha256:row.attachment_sha256,status:row.status,attempts:row.attempts,nextAttemptAt:row.next_attempt_at,leaseOwner:row.lease_owner,leaseExpiresAt:row.lease_expires_at,messageId:row.message_id,sentAt:row.sent_at,errorCode:row.error_code,redactedErrorMessage:row.redacted_error_message,createdAt:row.created_at,updatedAt:row.updated_at});
export class EmailOutboxRepository{
 constructor(private db:Database.Database=sessionRepository.getDatabase()){}
 activeCount(){return (this.db.prepare("SELECT COUNT(*) AS count FROM schedule_email_outbox WHERE status IN ('pending','preparing','sending','retry_wait','blocked_config','attachment_failed','delivery_unknown')").get() as {count:number}).count}
 sentSince(instant:string){return (this.db.prepare("SELECT COUNT(*) AS count FROM schedule_email_outbox WHERE status='sent' AND sent_at>=?").get(instant) as {count:number}).count}
 enqueue(input:{occurrenceId:string;configSnapshot:Record<string,unknown>;resultSnapshot:Record<string,unknown>;attachmentContent:Buffer;attachmentName:string;attachmentSha256:string;messageId:string}){
  const now=new Date().toISOString(),id=crypto.randomUUID();if(this.activeCount()>=500)throw new Error("EMAIL_BACKLOG_LIMIT");
  this.db.prepare("INSERT INTO schedule_email_outbox (id,occurrence_id,notification_type,config_snapshot_json,result_snapshot_json,attachment_content,attachment_name,attachment_encoding,attachment_sha256,status,attempts,next_attempt_at,lease_owner,lease_expires_at,message_id,sent_at,error_code,redacted_error_message,created_at,updated_at) VALUES (?,?,'job-result',?,?,?,?,'utf8',?,'pending',0,?,NULL,NULL,?,NULL,NULL,NULL,?,?) ON CONFLICT(occurrence_id,notification_type) DO NOTHING").run(id,input.occurrenceId,JSON.stringify(input.configSnapshot),JSON.stringify(input.resultSnapshot),input.attachmentContent,input.attachmentName,input.attachmentSha256,now,input.messageId,now,now);
  return this.findByOccurrence(input.occurrenceId);
 }
 findByOccurrence(id:string){const row=this.db.prepare("SELECT * FROM schedule_email_outbox WHERE occurrence_id=? AND notification_type='job-result'").get(id) as Row|undefined;return row?map(row):null}
 get(id:string){const row=this.db.prepare("SELECT * FROM schedule_email_outbox WHERE id=?").get(id) as Row|undefined;return row?map(row):null}
 claim(owner:string,now=new Date(),leaseMs=60_000){
  const instant=now.toISOString(),expires=new Date(now.getTime()+leaseMs).toISOString();
  return this.db.transaction(()=>{this.db.prepare("UPDATE schedule_email_outbox SET status='delivery_unknown',lease_owner=NULL,lease_expires_at=NULL,error_code='SMTP_PROCESS_INTERRUPTED',redacted_error_message='Tiến trình dừng khi email đang gửi; không tự gửi lại để tránh trùng',updated_at=? WHERE status='sending' AND lease_expires_at<=?").run(instant,instant);const row=this.db.prepare("SELECT * FROM schedule_email_outbox WHERE ((status IN ('pending','retry_wait') AND (next_attempt_at IS NULL OR next_attempt_at<=?)) OR (status='preparing' AND lease_expires_at<=?)) ORDER BY created_at LIMIT 1").get(instant,instant) as Row|undefined;if(!row)return null;const changed=this.db.prepare("UPDATE schedule_email_outbox SET status='preparing',lease_owner=?,lease_expires_at=?,attempts=attempts+1,updated_at=? WHERE id=? AND updated_at=?").run(owner,expires,instant,row.id,row.updated_at).changes;return changed?this.get(row.id):null;})();
 }
 markSending(id:string,owner:string){return this.updateOwned(id,owner,"status='sending'")}
 markSent(id:string,owner:string,sentAt:string){return this.updateOwned(id,owner,"status='sent',sent_at=?,lease_owner=NULL,lease_expires_at=NULL,error_code=NULL,redacted_error_message=NULL",sentAt)}
 markRetry(id:string,owner:string,nextAttemptAt:string,code:string,message:string){return this.updateOwned(id,owner,"status='retry_wait',next_attempt_at=?,lease_owner=NULL,lease_expires_at=NULL,error_code=?,redacted_error_message=?",nextAttemptAt,code,message)}
 markFinal(id:string,owner:string,status:"failed"|"blocked_config"|"attachment_failed"|"delivery_unknown",code:string,message:string){return this.updateOwned(id,owner,"status=?,lease_owner=NULL,lease_expires_at=NULL,error_code=?,redacted_error_message=?",status,code,message)}
 retry(id:string){const now=new Date().toISOString();return this.db.prepare("UPDATE schedule_email_outbox SET status='pending',next_attempt_at=?,lease_owner=NULL,lease_expires_at=NULL,error_code=NULL,redacted_error_message=NULL,updated_at=? WHERE id=? AND status IN ('failed','blocked_config','attachment_failed','delivery_unknown')").run(now,now,id).changes>0}
 cancelForSchedule(scheduleId:string){return this.db.prepare("UPDATE schedule_email_outbox SET status='cancelled',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE occurrence_id IN (SELECT id FROM schedule_occurrences WHERE schedule_id=?) AND status IN ('pending','preparing','retry_wait','blocked_config','attachment_failed')").run(new Date().toISOString(),scheduleId).changes}
 private updateOwned(id:string,owner:string,set:string,...values:unknown[]){const now=new Date().toISOString(),result=this.db.prepare("UPDATE schedule_email_outbox SET "+set+",updated_at=? WHERE id=? AND lease_owner=?").run(...values,now,id,owner);return result.changes?this.get(id):null}
}
export const emailOutboxRepository=new EmailOutboxRepository();
