import "@/lib/server/server-guard";
import {randomUUID} from "node:crypto";
import {eventBus} from "@/lib/server/event-bus";
import {safeError} from "@/lib/server/logging/redaction";
import {getEmailSettings} from "./email-settings";
import {withSavedEmailTransport} from "./email-transport";
import {emailOutboxRepository,EmailOutboxRepository,type EmailOutboxRecord} from "./email-outbox-repository";
type Sender=(item:EmailOutboxRecord)=>Promise<{messageId?:string}>;
const retryDelays=[60_000,5*60_000,15*60_000];
function classify(error:unknown,attempts:number){const message=safeError(error),code=String((error as {code?:unknown})?.code??"");if(/AUTH|CERT|recipient|address/i.test(code+" "+message))return{status:"failed" as const,code:code||"SMTP_PERMANENT",message};if(/DATA|socket closed|ECONNRESET/i.test(code+" "+message))return{status:"delivery_unknown" as const,code:code||"SMTP_DELIVERY_UNKNOWN",message};if(attempts>=4)return{status:"failed" as const,code:code||"SMTP_RETRIES_EXHAUSTED",message};return{status:"retry" as const,code:code||"SMTP_TEMPORARY",message};}
export class EmailWorker{
 private timer:NodeJS.Timeout|null=null;private active:Promise<void>|null=null;private stopping=false;private readonly owner=randomUUID();
 constructor(private repository:EmailOutboxRepository=emailOutboxRepository,private sender?:Sender,private now=()=>new Date(),private settings=getEmailSettings){}
 start(intervalMs=5000){if(this.timer)return;this.stopping=false;void this.kick();this.timer=setInterval(()=>void this.kick(),intervalMs)}
 private kick(){if(this.active||this.stopping)return this.active??Promise.resolve();const active=this.processOne().then(()=>undefined).finally(()=>{if(this.active===active)this.active=null});this.active=active;return active}
 async stop(){this.stopping=true;if(this.timer)clearInterval(this.timer);this.timer=null;await this.active}
 async processOne(){const hourAgo=new Date(this.now().getTime()-60*60_000).toISOString();if(this.repository.sentSince(hourAgo)>=30)return null;const item=this.repository.claim(this.owner,this.now());if(!item)return null;try{const config=item.configSnapshot as {to?:string;subject?:string;accountIdentity?:string},result=item.resultSnapshot as {body?:string,scheduleId?:string};const settings=await this.settings();if(!settings||!settings.passwordConfigured||settings.accountIdentity!==config.accountIdentity){this.repository.markFinal(item.id,this.owner,"blocked_config","EMAIL_CONFIG_CHANGED","Cấu hình tài khoản gửi không còn khớp snapshot");eventBus.emit("schedule.updated",{scheduleId:result.scheduleId,emailStatus:"blocked_config"});return item.id}if(!item.attachmentContent||!item.attachmentName){this.repository.markFinal(item.id,this.owner,"attachment_failed","EMAIL_ATTACHMENT_MISSING","Không có attachment bất biến");eventBus.emit("schedule.updated",{scheduleId:result.scheduleId,emailStatus:"attachment_failed"});return item.id}if(!this.repository.markSending(item.id,this.owner))return item.id;if(this.sender)await this.sender(item);else await withSavedEmailTransport(settings,transport=>transport.sendMail({from:settings.username,to:config.to,subject:config.subject,text:String(result.body??""),messageId:item.messageId??undefined,attachments:[{filename:item.attachmentName!,content:item.attachmentContent!,contentType:"text/plain; charset=utf-8"}]}));this.repository.markSent(item.id,this.owner,this.now().toISOString());eventBus.emit("schedule.updated",{scheduleId:result.scheduleId,emailStatus:"sent"});return item.id}catch(error){const current=this.repository.get(item.id)??item,outcome=classify(error,current.attempts);if(outcome.status==="retry"){const delay=retryDelays[Math.max(0,Math.min(retryDelays.length-1,current.attempts-1))];this.repository.markRetry(item.id,this.owner,new Date(this.now().getTime()+delay).toISOString(),outcome.code,outcome.message)}else this.repository.markFinal(item.id,this.owner,outcome.status,outcome.code,outcome.message);eventBus.emit("schedule.updated",{scheduleId:(item.resultSnapshot as {scheduleId?:string}).scheduleId,emailStatus:outcome.status==="retry"?"retry_wait":outcome.status});return item.id}}
}
export const emailWorker=new EmailWorker();
