import "@/lib/server/server-guard";
import type Database from "better-sqlite3";
import type {OccurrenceStatus,Schedule,ScheduleDetail,ScheduleOccurrence,ScheduleStatus} from "@/lib/contracts/types";
import {sessionRepository} from "@/lib/server/persistence/session-repository";
type SRow={id:string;name:string;start_date:string;local_time:string;timezone:string;repeat_days:number;prompt:string;device_serial:string;log_directory:string;status:ScheduleStatus;next_run_at:string|null;completed_occurrences:number;created_at:string;updated_at:string};
type ORow={id:string;schedule_id:string;scheduled_for:string;status:OccurrenceStatus;conversation_id:string|null;run_id:string|null;started_at:string|null;ended_at:string|null;result:string|null;error_code:string|null;error_message:string|null;log_file:string|null;created_at:string;updated_at:string};
const mapS=(r:SRow):Schedule=>({id:r.id,name:r.name,startDate:r.start_date,localTime:r.local_time,timezone:r.timezone,repeatDays:r.repeat_days,prompt:r.prompt,deviceSerial:r.device_serial,logDirectory:r.log_directory,status:r.status,nextRunAt:r.next_run_at,completedOccurrences:r.completed_occurrences,createdAt:r.created_at,updatedAt:r.updated_at});
const mapO=(r:ORow):ScheduleOccurrence=>({id:r.id,scheduleId:r.schedule_id,scheduledFor:r.scheduled_for,status:r.status,conversationId:r.conversation_id,runId:r.run_id,startedAt:r.started_at,endedAt:r.ended_at,result:r.result,errorCode:r.error_code,errorMessage:r.error_message,logFile:r.log_file,createdAt:r.created_at,updatedAt:r.updated_at});
export class ScheduleRepository{
 constructor(private db:Database.Database=sessionRepository.getDatabase()){}
 list(){return(this.db.prepare("SELECT * FROM schedules ORDER BY created_at DESC").all() as SRow[]).map(row=>{const schedule=mapS(row),latest=this.db.prepare("SELECT * FROM schedule_occurrences WHERE schedule_id=? ORDER BY scheduled_for DESC LIMIT 1").get(row.id) as ORow|undefined;return{...schedule,latestOccurrence:latest?mapO(latest):null}})}
 get(id:string):ScheduleDetail|null{const row=this.db.prepare("SELECT * FROM schedules WHERE id=?").get(id) as SRow|undefined;if(!row)return null;return{...mapS(row),occurrences:(this.db.prepare("SELECT * FROM schedule_occurrences WHERE schedule_id=? ORDER BY scheduled_for DESC").all(id) as ORow[]).map(mapO)}}
 create(input:Omit<Schedule,"id"|"status"|"completedOccurrences"|"createdAt"|"updatedAt">){const now=new Date().toISOString(),id=crypto.randomUUID();this.db.prepare("INSERT INTO schedules VALUES (?,?,?,?,?,?,?,?,?,'active',?,0,?,?)").run(id,input.name,input.startDate,input.localTime,input.timezone,input.repeatDays,input.prompt,input.deviceSerial,input.logDirectory,input.nextRunAt,now,now);return this.get(id)!}
 update(id:string,patch:Partial<Schedule>){const current=this.get(id);if(!current)return null;const n={...current,...patch,updatedAt:new Date().toISOString()};this.db.prepare("UPDATE schedules SET name=?,start_date=?,local_time=?,timezone=?,repeat_days=?,prompt=?,device_serial=?,log_directory=?,status=?,next_run_at=?,completed_occurrences=?,updated_at=? WHERE id=?").run(n.name,n.startDate,n.localTime,n.timezone,n.repeatDays,n.prompt,n.deviceSerial,n.logDirectory,n.status,n.nextRunAt,n.completedOccurrences,n.updatedAt,id);return this.get(id)}
 delete(id:string){return this.db.prepare("DELETE FROM schedules WHERE id=?").run(id).changes>0}
 due(now:string){return(this.db.prepare("SELECT * FROM schedules WHERE status='active' AND next_run_at IS NOT NULL AND next_run_at<=? ORDER BY next_run_at").all(now) as SRow[]).map(mapS)}
 createOccurrence(scheduleId:string,scheduledFor:string,status:OccurrenceStatus="pending"){const existing=this.db.prepare("SELECT * FROM schedule_occurrences WHERE schedule_id=? AND scheduled_for=?").get(scheduleId,scheduledFor) as ORow|undefined;if(existing)return mapO(existing);const now=new Date().toISOString(),id=crypto.randomUUID();try{this.db.prepare("INSERT INTO schedule_occurrences VALUES (?,?,?,?,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,?,?)").run(id,scheduleId,scheduledFor,status,now,now);return this.findOccurrence(id)!}catch{const raced=this.db.prepare("SELECT * FROM schedule_occurrences WHERE schedule_id=? AND scheduled_for=?").get(scheduleId,scheduledFor) as ORow|undefined;if(raced)return mapO(raced);throw new Error("Không thể tạo occurrence")}}
 updateOccurrence(id:string,patch:Partial<ScheduleOccurrence>){const current=this.findOccurrence(id);if(!current)return null;const n={...current,...patch,updatedAt:new Date().toISOString()};this.db.prepare("UPDATE schedule_occurrences SET status=?,conversation_id=?,run_id=?,started_at=?,ended_at=?,result=?,error_code=?,error_message=?,log_file=?,updated_at=? WHERE id=?").run(n.status,n.conversationId,n.runId,n.startedAt,n.endedAt,n.result,n.errorCode,n.errorMessage,n.logFile,n.updatedAt,id);return this.findOccurrence(id)}
 findOccurrence(id:string){const row=this.db.prepare("SELECT * FROM schedule_occurrences WHERE id=?").get(id) as ORow|undefined;return row?mapO(row):null}
 findByRun(runId:string){const row=this.db.prepare("SELECT * FROM schedule_occurrences WHERE run_id=?").get(runId) as ORow|undefined;return row?mapO(row):null}
 waiting(){return(this.db.prepare("SELECT * FROM schedule_occurrences WHERE status='waiting_device' ORDER BY created_at").all() as ORow[]).map(mapO)}
 running(){return(this.db.prepare("SELECT * FROM schedule_occurrences WHERE status='running'").all() as ORow[]).map(mapO)}
 recentLogFailures(scheduleId:string,limit=3){return(this.db.prepare("SELECT error_code FROM schedule_occurrences WHERE schedule_id=? ORDER BY updated_at DESC LIMIT ?").all(scheduleId,limit) as {error_code:string|null}[]).filter(row=>row.error_code==="LOG_WRITE_FAILED").length}
 pruneOccurrences(days=365){const cutoff=new Date(Date.now()-days*86400000).toISOString();return this.db.prepare("DELETE FROM schedule_occurrences WHERE updated_at<? AND status IN ('completed','failed','missed','cancelled')").run(cutoff).changes}
}
export const scheduleRepository=new ScheduleRepository();
