import type {Schedule,ScheduleRule} from "@/lib/contracts/types";
export type ScheduleTiming={startDate:string;localTime:string;timezone:string;rule:ScheduleRule;occurrenceLimit:number|null;completedOccurrences?:number};
const parts=(date:string,time:string)=>{const [year,month,day]=date.split("-").map(Number),[hour,minute]=time.split(":").map(Number),check=new Date(Date.UTC(year,month-1,day));if(!year||!month||!day||check.getUTCFullYear()!==year||check.getUTCMonth()!==month-1||check.getUTCDate()!==day||hour===undefined||minute===undefined)throw new Error("Ngày giờ không hợp lệ");return{year,month,day,hour,minute}};
const formatter=(timeZone:string)=>new Intl.DateTimeFormat("en-US",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});
export function localDateTimeToUtc(date:string,time:string,timeZone:string){const p=parts(date,time);let utc=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute);for(let i=0;i<3;i++){const v=Object.fromEntries(formatter(timeZone).formatToParts(new Date(utc)).filter(x=>x.type!=="literal").map(x=>[x.type,Number(x.value)]));utc+=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute)-Date.UTC(v.year,v.month-1,v.day,v.hour,v.minute,v.second)}const result=new Date(utc),v=Object.fromEntries(formatter(timeZone).formatToParts(result).filter(x=>x.type!=="literal").map(x=>[x.type,Number(x.value)]));if(v.year!==p.year||v.month!==p.month||v.day!==p.day||v.hour!==p.hour||v.minute!==p.minute)throw new Error("Giờ địa phương không tồn tại trong múi giờ");return result.toISOString()}
export function addCalendarDays(date:string,days:number){const p=parts(date,"00:00"),next=new Date(Date.UTC(p.year,p.month-1,p.day+days));return next.toISOString().slice(0,10)}
const isoWeekday=(date:string)=>{const day=new Date(date+"T00:00:00Z").getUTCDay();return day===0?7:day};
const localDate=(instant:string,timeZone:string)=>{const v=Object.fromEntries(formatter(timeZone).formatToParts(new Date(instant)).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));return v.year+"-"+v.month+"-"+v.day};
export function firstOccurrence(input:ScheduleTiming){let date=input.startDate;if(input.rule.type==="weekly")while(!input.rule.weekdays.includes(isoWeekday(date) as 1|2|3|4|5|6|7))date=addCalendarDays(date,1);return localDateTimeToUtc(date,input.localTime,input.timezone)}
const advanceFrom=(schedule:Pick<Schedule,"localTime"|"timezone"|"rule">,previous:string)=>{if(schedule.rule.type==="interval"){const ms=schedule.rule.every*(schedule.rule.unit==="seconds"?1000:schedule.rule.unit==="minutes"?60000:3600000);return new Date(Date.parse(previous)+ms).toISOString()}let date=addCalendarDays(localDate(previous,schedule.timezone),1);if(schedule.rule.type==="weekly")while(!schedule.rule.weekdays.includes(isoWeekday(date) as 1|2|3|4|5|6|7))date=addCalendarDays(date,1);return localDateTimeToUtc(date,schedule.localTime,schedule.timezone)};
export function nextOccurrence(schedule:Pick<Schedule,"startDate"|"localTime"|"timezone"|"rule"|"occurrenceLimit"|"completedOccurrences">,previousScheduledFor?:string){if(schedule.occurrenceLimit!==null&&schedule.completedOccurrences>=schedule.occurrenceLimit)return null;if(previousScheduledFor)return advanceFrom(schedule,previousScheduledFor);let occurrence=firstOccurrence(schedule);for(let index=0;index<schedule.completedOccurrences;index++)occurrence=advanceFrom(schedule,occurrence);return occurrence}
export function nextFutureOccurrence(schedule:Pick<Schedule,"startDate"|"localTime"|"timezone"|"rule"|"occurrenceLimit"|"completedOccurrences">,previousScheduledFor:string,now:string){let next=advanceFrom(schedule,previousScheduledFor);if(schedule.rule.type==="interval"){const ms=schedule.rule.every*(schedule.rule.unit==="seconds"?1000:schedule.rule.unit==="minutes"?60000:3600000),steps=Math.max(0,Math.floor((Date.parse(now)-Date.parse(next))/ms)+1);if(steps)next=new Date(Date.parse(next)+steps*ms).toISOString();return next}for(let i=0;i<366&&Date.parse(next)<=Date.parse(now);i++)next=advanceFrom(schedule,next);return next}
export function previewOccurrences(input:ScheduleTiming,count=Math.min(3,input.occurrenceLimit??3)){const result:string[]=[];let current=firstOccurrence(input);for(let i=0;i<Math.min(count,input.occurrenceLimit??count);i++){result.push(current);const next=nextOccurrence({...input,completedOccurrences:i+1},current);if(!next)break;current=next}return result}
