import "@/lib/server/server-guard";
import {scheduleRepository,ScheduleRepository} from "./schedule-repository";
import {nextFutureOccurrence,nextOccurrence} from "./schedule-calculator";
import {scheduleLogWriter,ScheduleLogWriter} from "./schedule-log-writer";
import {sessionRepository,SessionRepository} from "@/lib/server/persistence/session-repository";
import {runService,RunService} from "@/lib/server/agent/run-service";
import {eventBus} from "@/lib/server/event-bus";
import {getRuntimeSettings} from "@/lib/server/runtime-settings";
import type {AppEvent,Schedule,ScheduleOccurrence} from "@/lib/contracts/types";
const MISSED_GRACE_MS=15*60_000,DEVICE_BUSY_GRACE_MS=10*60_000;
export class ScheduleService{
 private timer:NodeJS.Timeout|null=null;private ticking=false;private unsubscribe=()=>{};
 constructor(private repository:ScheduleRepository=scheduleRepository,private logs:ScheduleLogWriter=scheduleLogWriter,private now=()=>new Date(),private runs:RunService=runService,private sessions:SessionRepository=sessionRepository){}
 start(intervalMs=15000){if(this.timer)return;this.unsubscribe=eventBus.subscribe(event=>void this.onEvent(event));void this.reconcile();void this.tick();this.timer=setInterval(()=>void this.tick(),intervalMs)}
 stop(){if(this.timer)clearInterval(this.timer);this.timer=null;this.unsubscribe()}
 async runNow(schedule:Schedule){return this.launchNew(schedule,this.now().toISOString(),false)}
 async tick(){if(this.ticking)return;this.ticking=true;try{const now=this.now();for(const occurrence of this.repository.waiting())await this.retryWaiting(occurrence,now);for(const schedule of this.repository.due(now.toISOString())){const late=now.getTime()-new Date(schedule.nextRunAt!).getTime();if(late>MISSED_GRACE_MS)await this.failNew(schedule,schedule.nextRunAt!,"missed","MISSED","Server không hoạt động trong thời gian chạy");else await this.launchNew(schedule,schedule.nextRunAt!,true)}}finally{this.ticking=false}}
 private async launchNew(schedule:Schedule,scheduledFor:string,counted:boolean){const occurrence=this.repository.createOccurrence(schedule.id,scheduledFor);if(!occurrence||occurrence.status!=="pending")return occurrence;return this.tryLaunch(schedule,occurrence,counted)}
 private async tryLaunch(schedule:Schedule,occurrence:ScheduleOccurrence,counted:boolean){let conversationId:string|null=null;try{const title="[Lịch] "+schedule.name+" · "+occurrence.scheduledFor.slice(0,16).replace("T"," "),conversation=this.sessions.create(title);conversationId=conversation.id;const run=await this.runs.createAndStart({conversationId:conversation.id,deviceSerial:schedule.deviceSerial,goal:schedule.prompt,maxSteps:getRuntimeSettings().maxSteps,source:"schedule",scheduleOccurrenceId:occurrence.id});const updated=this.repository.updateOccurrence(occurrence.id,{status:"running",conversationId:conversation.id,runId:run.id,startedAt:this.now().toISOString()})!;if(counted)this.advance(schedule,occurrence.scheduledFor);eventBus.emit("schedule.updated",{scheduleId:schedule.id,occurrenceId:updated.id,status:"running",conversationId:conversation.id,runId:run.id,deviceSerial:schedule.deviceSerial});return updated}catch(error){if(conversationId)try{this.sessions.deleteConversation(conversationId)}catch{}const message=error instanceof Error?error.message:String(error);if(counted&&/already active|đang được|đang sử dụng|another agent/i.test(message)){const waiting=this.repository.updateOccurrence(occurrence.id,{status:"waiting_device",errorCode:null,errorMessage:null})!;eventBus.emit("schedule.updated",{scheduleId:schedule.id,occurrenceId:waiting.id,status:"waiting_device"});return waiting}return this.failExisting(schedule,occurrence,"DEVICE_UNAVAILABLE",message,counted)}}
 private async retryWaiting(occurrence:ScheduleOccurrence,now:Date){const schedule=this.repository.get(occurrence.scheduleId);if(!schedule)return;if(now.getTime()-new Date(occurrence.createdAt).getTime()>DEVICE_BUSY_GRACE_MS)return this.failExisting(schedule,occurrence,"DEVICE_BUSY_TIMEOUT","Thiết bị bận quá thời gian chờ",true);return this.tryLaunch(schedule,occurrence,true)}
 private advance(schedule:Schedule,previousScheduledFor:string){const completed=schedule.completedOccurrences+1,next={...schedule,completedOccurrences:completed};let nextRunAt=nextOccurrence(next,previousScheduledFor);if(nextRunAt&&schedule.rule.type==="interval"&&Date.parse(nextRunAt)<=this.now().getTime())nextRunAt=nextFutureOccurrence(next,previousScheduledFor,this.now().toISOString());const status=nextRunAt?"active":"completed";this.repository.update(schedule.id,{completedOccurrences:completed,nextRunAt,status})}
 private async failNew(schedule:Schedule,scheduledFor:string,status:"failed"|"missed",code:string,message:string){const occurrence=this.repository.createOccurrence(schedule.id,scheduledFor,status);if(!occurrence)return null;const updated=this.repository.updateOccurrence(occurrence.id,{status,errorCode:code,errorMessage:message,endedAt:this.now().toISOString()})!;this.advance(schedule,scheduledFor);await this.write(schedule,updated);eventBus.emit("schedule.updated",{scheduleId:schedule.id,occurrenceId:updated.id,status});return updated}
 private async failExisting(schedule:Schedule,occurrence:ScheduleOccurrence,code:string,message:string,counted:boolean){const updated=this.repository.updateOccurrence(occurrence.id,{status:"failed",errorCode:code,errorMessage:message,endedAt:this.now().toISOString()})!;if(counted)this.advance(schedule,occurrence.scheduledFor);await this.write(schedule,updated);eventBus.emit("schedule.updated",{scheduleId:schedule.id,occurrenceId:updated.id,status:"failed"});return updated}
 private async onEvent(event:AppEvent){if(!event.runId||!["run.completed","run.failed","run.cancelled"].includes(event.type))return;const occurrence=this.repository.findByRun(event.runId);if(!occurrence||["completed","failed","cancelled"].includes(occurrence.status))return;const run=this.sessions.findRun(event.runId);if(!run)return;const status=run.status==="completed"?"completed":run.status==="cancelled"?"cancelled":"failed",updated=this.repository.updateOccurrence(occurrence.id,{status,result:run.result,errorCode:run.errorCode,errorMessage:run.status==="failed"?run.result:null,endedAt:run.endedAt||this.now().toISOString()})!;const schedule=this.repository.get(occurrence.scheduleId);if(schedule)await this.write(schedule,updated);eventBus.emit("schedule.updated",{scheduleId:occurrence.scheduleId,occurrenceId:occurrence.id,status})}
 private async write(schedule:Schedule,occurrence:ScheduleOccurrence){try{const file=await this.logs.write(schedule,occurrence);this.repository.updateOccurrence(occurrence.id,{logFile:file})}catch(error){this.repository.updateOccurrence(occurrence.id,{errorCode:"LOG_WRITE_FAILED",errorMessage:(occurrence.errorMessage?occurrence.errorMessage+"; ":"")+String(error)});if(this.repository.recentLogFailures(schedule.id,3)>=3){this.repository.update(schedule.id,{status:"disabled",nextRunAt:null});eventBus.emit("schedule.updated",{scheduleId:schedule.id,status:"disabled",reason:"LOG_WRITE_FAILED"})}}}
 async reconcile(){for(const occurrence of this.repository.running()){const run=occurrence.runId?this.sessions.findRun(occurrence.runId):null;if(run&&["completed","failed","cancelled"].includes(run.status))await this.onEvent({eventId:crypto.randomUUID(),type:"run."+run.status,runId:run.id,data:{},createdAt:this.now().toISOString()});else if(!run){const schedule=this.repository.get(occurrence.scheduleId);if(schedule)await this.failExisting(schedule,occurrence,"SERVER_RESTARTED","Run không còn hoạt động sau khi server khởi động lại",false)}}}
}
export const scheduleService=new ScheduleService();
