import "@/lib/server/server-guard";
import fs from "node:fs";
import path from "node:path";
import {pathToFileURL} from "node:url";
import {execFileSync} from "node:child_process";
import {createHash} from "node:crypto";
import type {IncomingMessage} from "node:http";
import type {Duplex} from "node:stream";
import {WebSocketServer,type WebSocket} from "ws";
import {scrcpyBridgeStatus} from "@/lib/server/scrcpy/bridge-status";
import {streamSessionManager} from "@/lib/server/scrcpy/stream-session-manager";
export function isScrcpyUpgradeAuthorized(request:IncomingMessage){const url=new URL(request.url||"/","http://"+(request.headers.host||"localhost"));let originOk=false;try{originOk=new URL(request.headers.origin||"").host===request.headers.host}catch{}const token=url.searchParams.get("session")||"",serial=url.searchParams.get("serial")||"";return originOk&&Boolean(serial)&&streamSessionManager.resolve(token,false)?.serial===serial}
export class GplScrcpyBridge{
 private wss=new WebSocketServer({noServer:true});private clients=new Set<WebSocket>();private ready=false;private ScrcpyConnection:any;
 async initialize(){if(process.env.SCRCPY_INTEGRATION!=="gplv3")return;const vendor=path.join(process.cwd(),"vendor","ws-scrcpy-web"),deps=path.join(process.cwd(),"data","scrcpy-dependencies"),serverDir=path.join(deps,"scrcpy-server"),configDir=path.join(process.cwd(),"data","ws-scrcpy");fs.mkdirSync(serverDir,{recursive:true});fs.mkdirSync(configDir,{recursive:true});const serverSource=path.join(vendor,"assets","scrcpy-server"),serverHash=createHash("sha256").update(fs.readFileSync(serverSource)).digest("hex");if(serverHash!=="deacb991ed2509715160ffdc7907e47b4160eb30d1566217e9047fd5b8850cae")throw new Error("scrcpy-server checksum mismatch");fs.copyFileSync(serverSource,path.join(serverDir,"scrcpy-server"));fs.writeFileSync(path.join(serverDir,".version"),"4.1\n");const adbDir=path.join(deps,"adb"),adbExe=path.join(adbDir,"adb.exe");fs.mkdirSync(adbDir,{recursive:true});if(!fs.existsSync(adbExe)){const configured=process.env.ADB_PATH;const discovered=configured||execFileSync("where.exe",["adb"],{encoding:"utf8"}).split(/\r?\n/).find(Boolean);if(!discovered)throw new Error("ADB executable not found for scrcpy bridge");const source=path.resolve(discovered.trim());fs.copyFileSync(source,adbExe);for(const dll of ["AdbWinApi.dll","AdbWinUsbApi.dll"]){const candidate=path.join(path.dirname(source),dll);if(fs.existsSync(candidate))fs.copyFileSync(candidate,path.join(adbDir,dll))}}const configPath=path.join(configDir,"config.json");fs.writeFileSync(configPath,JSON.stringify({adbPath:process.env.ADB_PATH||"adb",dependenciesPath:deps,firstRunComplete:true},null,2));process.env.CONFIG_PATH=configPath;process.env.DEPS_PATH=deps;this.ScrcpyConnection=(await import(pathToFileURL(path.join(vendor,"src","server","ScrcpyConnection.ts")).href)).ScrcpyConnection;this.wss.on("connection",(ws,request)=>{this.clients.add(ws);scrcpyBridgeStatus.clients=this.clients.size;ws.on("close",()=>{this.clients.delete(ws);scrcpyBridgeStatus.clients=this.clients.size});const url=new URL(request.url||"/","http://localhost"),serial=url.searchParams.get("serial")||"",token=url.searchParams.get("session")||"",resolved=streamSessionManager.resolve(token);if(!resolved||resolved.serial!==serial){ws.close(4401,"invalid stream session");return}url.searchParams.set("action","stream");url.searchParams.set("udid",serial);const service=this.ScrcpyConnection.processRequest(ws,{action:"stream",request,url});if(!service)ws.close(4002,"unsupported scrcpy request")});this.ready=true;scrcpyBridgeStatus.available=true}
 handleUpgrade(request:IncomingMessage,socket:Duplex,head:Buffer){if(!this.ready){socket.write("HTTP/1.1 503 Service Unavailable\r\nConnection: close\r\n\r\n");socket.destroy();return}if(!isScrcpyUpgradeAuthorized(request)){socket.write("HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n");socket.destroy();return}this.wss.handleUpgrade(request,socket,head,ws=>this.wss.emit("connection",ws,request))}
 close(){for(const client of this.clients)client.terminate();this.clients.clear();this.wss.close();this.ready=false;scrcpyBridgeStatus.available=false;scrcpyBridgeStatus.clients=0}stats(){return{available:this.ready,clients:this.clients.size}}
}
export const gplScrcpyBridge=new GplScrcpyBridge();
