import {adbService} from "@/lib/server/adb/adb-service";
import {deviceManager} from "@/lib/server/adb/device-manager";
import {uiHierarchyService} from "@/lib/server/adb/ui-hierarchy";
import {deviceControlService} from "@/lib/server/scrcpy/device-control-service";
import {modelClient} from "@/lib/server/model/model-client";
import {sessionRepository} from "@/lib/server/persistence/session-repository";
import {eventBus} from "@/lib/server/event-bus";
import type {RunRecord} from "@/lib/contracts/types";
const sleep=(ms:number,signal:AbortSignal)=>new Promise<void>((resolve,reject)=>{const t=setTimeout(resolve,ms);signal.addEventListener("abort",()=>{clearTimeout(t);reject(new DOMException("Aborted","AbortError"))},{once:true})});
type Active={controller:AbortController;pauseRequested:boolean;resume?:()=>void};
class AgentRunner {
 private active=new Map<string,Active>();
 start(run:RunRecord){if([...this.active.keys()].some(id=>sessionRepository.findRun(id)?.deviceSerial===run.deviceSerial))throw new Error("An agent is already active on this device");const state:Active={controller:new AbortController(),pauseRequested:false};this.active.set(run.id,state);void this.loop(run,state);return run}
 pause(id:string){const s=this.active.get(id),r=sessionRepository.findRun(id);if(!s||!r||r.status!=="running")throw new Error("Run is not running");s.pauseRequested=true;sessionRepository.updateRun(id,{status:"pausing"});eventBus.emit("run.status",{status:"pausing"},{conversationId:r.conversationId,runId:id})}
 resume(id:string){const s=this.active.get(id),r=sessionRepository.findRun(id);if(!s||!r||r.status!=="paused")throw new Error("Run is not paused");s.pauseRequested=false;s.resume?.();s.resume=undefined;sessionRepository.updateRun(id,{status:"running"});eventBus.emit("run.status",{status:"running"},{conversationId:r.conversationId,runId:id})}
 cancel(id:string){const s=this.active.get(id),r=sessionRepository.findRun(id);if(!s||!r)return;sessionRepository.updateRun(id,{status:"cancelling"});s.controller.abort();s.resume?.();eventBus.emit("run.status",{status:"cancelling"},{conversationId:r.conversationId,runId:id})}
 private async checkpoint(run:RunRecord,s:Active){s.controller.signal.throwIfAborted();if(s.pauseRequested){sessionRepository.updateRun(run.id,{status:"paused"});eventBus.emit("run.status",{status:"paused"},{conversationId:run.conversationId,runId:run.id});await new Promise<void>(resolve=>s.resume=resolve);s.controller.signal.throwIfAborted()}}
 private async loop(run:RunRecord,s:Active){try{sessionRepository.updateRun(run.id,{status:"running"});eventBus.emit("run.status",{status:"running"},{conversationId:run.conversationId,runId:run.id});for(let step=1;step<=run.maxSteps;step++){await this.checkpoint(run,s);const device=await deviceManager.requireConnected(run.deviceSerial);eventBus.emit("run.step.started",{step,maxSteps:run.maxSteps},{conversationId:run.conversationId,runId:run.id});const capture=await adbService.run(["exec-out","screencap","-p"],{serial:run.deviceSerial,signal:s.controller.signal,timeoutMs:15000});await this.checkpoint(run,s);const elements=await uiHierarchyService.getClickableElements(run.deviceSerial);const action=await modelClient.nextAction({goal:run.goal,imageBase64:capture.stdout.toString("base64"),uiContext:uiHierarchyService.format(elements,device.width||1080,device.height||2400),history:run.steps,signal:s.controller.signal});await this.checkpoint(run,s);if(action.action==="finish"){sessionRepository.addStep(run.id,action,action.thought,null);sessionRepository.updateRun(run.id,{status:"completed",result:action.thought,endedAt:new Date().toISOString()});sessionRepository.addMessage(run.conversationId,"assistant",action.thought);eventBus.emit("run.completed",{result:action.thought},{conversationId:run.conversationId,runId:run.id});return}const started=Date.now();await deviceControlService.execute(run.deviceSerial,action,s.controller.signal);const saved=sessionRepository.addStep(run.id,action,action.thought,Date.now()-started);eventBus.emit("run.step.action",saved,{conversationId:run.conversationId,runId:run.id});await sleep(1500,s.controller.signal)}throw Object.assign(new Error("Reached maximum steps without completion"),{code:"MAX_STEPS"})}catch(error){const aborted=s.controller.signal.aborted;const message=error instanceof Error?error.message:String(error);sessionRepository.updateRun(run.id,{status:aborted?"cancelled":"failed",errorCode:aborted?"CANCELLED":((error as {code?:string}).code||"RUN_ERROR"),result:message,endedAt:new Date().toISOString()});sessionRepository.addMessage(run.conversationId,"assistant",aborted?"Đã dừng tác vụ.":"Lỗi: "+message);eventBus.emit(aborted?"run.cancelled":"run.failed",{error:message},{conversationId:run.conversationId,runId:run.id})}finally{this.active.delete(run.id)}}
}
export const agentRunner=new AgentRunner();
